/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup Drawing
 * @{
 *
 * @brief Provides the text run capability.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 *
 * @since 18
 * @version 1.0
 */

/**
 * @file drawing_text_run.h
 *
 * @brief This file declares the capabilities of runs, such as obtaining the typographic boundary and drawing.
 *
 * @kit ArkGraphics2D
 * @library libnative_drawing.so
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @since 18
 * @version 1.0
 */

#ifndef C_INCLUDE_DRAWING_TEXT_RUN_H
#define C_INCLUDE_DRAWING_TEXT_RUN_H

#include "drawing_text_declaration.h"
#include "drawing_text_typography.h"
#include "drawing_types.h"

#ifdef __cplusplus
extern "C" {
#endif
/**
 * @brief Obtains an array of character indices of glyphs within a specified range of a run, where the indices are
 * offsets relative to the entire paragraph.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @param start Start position specified within the rendering unit. The value range is [0, glyphCount-1], where
 *     glyphCount is the glyph count of the rendering unit. The method returns a null pointer when passing a negative
 *     number or a value that exceeds the glyph count of the rendering unit.
 * @param length Length specified within the rendering unit. When length is 0, the method obtains the character index
 *     array of all characters in the rendering unit. When length is less than 0, the method returns a null pointer.
 *     When start+length exceeds the actual range of the rendering unit, the method obtains valid data up to the end of
 *     the rendering unit.
 * @return Returns the character index array of the glyph. Call {@link OH_Drawing_DestroyRunStringIndices} to release
 *     this pointer when the object is no longer needed.
 * @since 18
 */
OH_Drawing_Array* OH_Drawing_GetRunStringIndices(OH_Drawing_Run* run, int64_t start, int64_t length);

/**
 * @brief Obtains character indices of glyphs in a run by index.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param stringIndices Pointer to a character index array.
 * @param index Subscript of the character index array for the rendering unit glyphs. The value range is [0,
 *     arrayLength-1], where arrayLength is the number of elements in the stringIndices array. 0 is returned when the
 *     value exceeds this range.
 * @return Returns the character indices.
 * @since 18
 */
uint64_t OH_Drawing_GetRunStringIndicesByIndex(OH_Drawing_Array* stringIndices, size_t index);

/**
 * @brief Releases the pointer to a character index array object.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param stringIndices Pointer to a character index array.
 * @since 18
 */
void OH_Drawing_DestroyRunStringIndices(OH_Drawing_Array* stringIndices);

/**
 * @brief Obtains the range of glyphs generated by a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @param location Start position of the character range of the rendering unit glyph, which is an offset relative to
 *     the whole paragraph. This is an output parameter. The caller must provide a valid pointer to receive the return
 *     value.
 * @param length Length of the character range of the rendering unit. This is an output parameter. The caller must
 *     provide a valid pointer to receive the return value.
 * @since 18
 */
void OH_Drawing_GetRunStringRange(OH_Drawing_Run* run, uint64_t* location, uint64_t* length);

/**
 * @brief Obtains the typographic boundary of a run. The typographic boundary is related to the font and font size used
 * for typography, but not the characters within the text.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @param ascent Pointer to the distance from the highest character in the rendering unit to the baseline, in px.
 * @param descent Pointer to the distance from the lowest character in the rendering unit to the baseline, in px.
 * @param leading Pointer to the line spacing of the rendering unit, in px.
 * @return Typographic width of the rendering unit, in px.
 * @since 18
 */
float OH_Drawing_GetRunTypographicBounds(OH_Drawing_Run* run, float* ascent, float* descent, float* leading);

/**
 * @brief Paints the text contained in a run on the canvas.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param canvas Pointer to an {@link OH_Drawing_Canvas} object.
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @param x X coordinate of the rendering unit, in px.
 * @param y Y coordinate of the rendering unit, in px.
 * @since 18
 */
void OH_Drawing_RunPaint(OH_Drawing_Canvas* canvas, OH_Drawing_Run* run, double x, double y);

/**
 * @brief Obtains the image boundary of a run. The image boundary is related to characters and is equivalent to the
 * visual boundary.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @return Returns the pointer to an {@link OH_Drawing_Rect} object. Call {@link OH_Drawing_DestroyRunImageBounds} to
 *     release this pointer when the object is no longer needed.
 * @since 18
 */
OH_Drawing_Rect* OH_Drawing_GetRunImageBounds(OH_Drawing_Run* run);

/**
 * @brief Releases the pointer to an image boundary object of a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param rect Pointer to the image boundary, which is an {@link OH_Drawing_Rect} object.
 * @since 18
 */
void OH_Drawing_DestroyRunImageBounds(OH_Drawing_Rect* rect);

/**
 * @brief Obtains an array of glyphs within the specified range of a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @param start Start position specified within the rendering unit. The value range is [0, glyphCount-1], where
 *     glyphCount is the number of glyphs in the rendering unit. When a negative number is passed or the value exceeds
 *     the number of glyphs in the rendering unit, the method returns a null pointer.
 * @param length Length specified within the rendering unit. When length is 0, all glyphs of the rendering unit are
 *     obtained. When length is less than 0, the method returns a null pointer. When start+length exceeds the actual
 *     range of the rendering unit, valid data up to the end of the rendering unit is obtained.
 * @return Returns the pointer to an {@link OH_Drawing_Array} object of a glyph array in a run. Call
 *     {@link OH_Drawing_DestroyRunGlyphs} to release this pointer when the object is no longer needed.
 * @since 18
 */
OH_Drawing_Array* OH_Drawing_GetRunGlyphs(OH_Drawing_Run* run, int64_t start, int64_t length);

/**
 * @brief Obtains individual glyphs in a run by index.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param glyphs Pointer to the glyph array, which is an {@link OH_Drawing_Array} object.
 * @param index Subscript of the rendering unit glyph array. The value range is [0, arrayLength-1], where arrayLength
 *     is the number of elements in the glyphs array. 0 is returned when the value exceeds this range.
 * @return Glyph ID of a single glyph in the rendering unit.
 * @since 18
 * @version 1.0
 */
uint16_t OH_Drawing_GetRunGlyphsByIndex(OH_Drawing_Array* glyphs, size_t index);

/**
 * @brief Releases the pointer to a glyph array in a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param glyphs Pointer to the glyph array, which is an {@link OH_Drawing_Array} object.
 * @since 18
 */
void OH_Drawing_DestroyRunGlyphs(OH_Drawing_Array* glyphs);

/**
 * @brief Obtains the positions of glyphs within the specified range of a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @param start Start position specified within the rendering unit. The value range is [0, glyphCount-1], where
 *     glyphCount is the glyph count of the rendering unit. The method returns a null pointer when a negative number is
 *     passed or when the value exceeds the glyph count of the rendering unit.
 * @param length Length specified within the rendering unit. When length is 0, all glyph positions of the rendering
 *     unit are obtained. The method returns a null pointer when length is less than 0. When start+length exceeds the
 *     actual range of the rendering unit, valid data up to the end of the rendering unit is obtained.
 * @return Returns the pointer to an {@link OH_Drawing_Array} object of a glyph position array in a run. Call
 *     {@link OH_Drawing_DestroyRunPositions} to release this pointer when the object is no longer needed.
 * @since 18
 */
OH_Drawing_Array* OH_Drawing_GetRunPositions(OH_Drawing_Run* run, int64_t start, int64_t length);

/**
 * @brief Obtains the positions of individual glyphs in a run by index.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param positions Pointer to the glyph position array, which is an {@link OH_Drawing_Array} object.
 * @param index Subscript of the rendering unit glyph position array. The value range is [0, arrayLength-1], where
 *     arrayLength is the number of elements in the positions array. The method returns null pointer when the value
 *     exceeds the range.
 * @return Returns the pointer to an {@link OH_Drawing_Point} object, which holds the positions of individual glyphs in
 *     the run.
 * @since 18
 * @version 1.0
 */
OH_Drawing_Point* OH_Drawing_GetRunPositionsByIndex(OH_Drawing_Array* positions, size_t index);

/**
 * @brief Releases the pointer to a glyph position array in a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param positions Pointer to the glyph position array, which is an {@link OH_Drawing_Array} object.
 * @since 18
 */
void OH_Drawing_DestroyRunPositions(OH_Drawing_Array* positions);

/**
 * @brief Obtains the number of glyphs in a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @return Returns the number of glyphs.
 * @since 18
 */
uint32_t OH_Drawing_GetRunGlyphCount(OH_Drawing_Run* run);

/**
 * @brief Obtains the font object of a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @return Returns the pointer to an {@link OH_Drawing_Font} object in a run. Call {@link OH_Drawing_FontDestroy} to
 *     release this pointer when the object is no longer needed.
 * @since 20
 * @version 1.0
 */
OH_Drawing_Font* OH_Drawing_GetRunFont(OH_Drawing_Run* run);

/**
 * @brief Obtains the text direction of a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @return Returns the text direction of a run. **0**: **TEXT_DIRECTION_RTL**, which means right-to-left; **1**: **
 *     TEXT_DIRECTION_LTR**, which means left-to-right. For details, see {@link OH_Drawing_TextDirection}.
 * @since 20
 */
OH_Drawing_TextDirection OH_Drawing_GetRunTextDirection(OH_Drawing_Run* run);

/**
 * @brief Obtains the glyph advance array of a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param run Pointer to an {@link OH_Drawing_Run} object.
 * @param start Start position specified within the rendering unit. The value range is [0, glyphCount-1], where
 *     glyphCount is the glyph count of the rendering unit. If the passed value exceeds the glyph count of the
 *     rendering unit, the method returns null pointer.
 * @param length Length specified within the rendering unit. When length is 0, obtains the widths of all glyphs from
 *     start to the end of the rendering unit.
 * @return Returns the pointer to an {@link OH_Drawing_Array} object of a glyph advance array in a run. Call
 *     {@link OH_Drawing_DestroyRunGlyphAdvances} to release this pointer when the object is no longer needed.
 * @since 20
 */
OH_Drawing_Array* OH_Drawing_GetRunGlyphAdvances(OH_Drawing_Run* run, uint32_t start, uint32_t length);

/**
 * @brief Obtains the advances of individual glyphs in a run by index.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param advances Pointer to the glyph advance array, which is an {@link OH_Drawing_Array} object.
 * @param index Subscript of the rendering unit glyph width array. The value range is [0, arrayLength-1], where
 *     arrayLength is the number of elements in the advances array. A null pointer is returned when the value exceeds
 *     the range.
 * @return Returns the pointer to an {@link OH_Drawing_Point} object, which holds the advance of individual glyphs in
 *     the run. **x** indicates the advance, and **y** is a reserved field and defaults to **0**.
 * @since 20
 */
OH_Drawing_Point* OH_Drawing_GetRunGlyphAdvanceByIndex(OH_Drawing_Array* advances, size_t index);

/**
 * @brief Releases the pointer to a glyph advance array in a run.
 *
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @param advances Pointer to the glyph advance array, which is an {@link OH_Drawing_Array} object.
 * @since 20
 */
void OH_Drawing_DestroyRunGlyphAdvances(OH_Drawing_Array* advances);
#ifdef __cplusplus
}
#endif
/** @} */
#endif // C_INCLUDE_DRAWING_TEXT_RUN_H