/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup Drawing
 * @{
 *
 * @brief Provides functions such as 2D graphics rendering, text drawing, and image display.
 *
 * @since 8
 * @version 1.0
 */
/**
 * @file drawing_error_code.h
 *
 * @brief This file declares the functions related to the error code in the drawing module.
 *
 * @kit ArkGraphics2D
 * @library libnative_drawing.so
 * @syscap SystemCapability.Graphic.Graphic2D.NativeDrawing
 * @since 12
 * @version 1.0
 */

#ifndef C_INCLUDE_DRAWING_ERROR_CODE_H
#define C_INCLUDE_DRAWING_ERROR_CODE_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Defines an enum for the error codes that may be generated by the module.
 *
 * @since 12
 */
typedef enum {
    /**
     * Operation successful.
     *
     * @since 12
     */
    OH_DRAWING_SUCCESS = 0,
    /**
     * Permission denied.
     *
     * @since 12
     */
    OH_DRAWING_ERROR_NO_PERMISSION = 201,
    /**
     * Invalid input parameter. For example, NULL is passed in.
     *
     * @since 12
     */
    OH_DRAWING_ERROR_INVALID_PARAMETER = 401,
    /**
     * The input parameter is not in the valid range.
     *
     * @since 12
     */
    OH_DRAWING_ERROR_PARAMETER_OUT_OF_RANGE = 26200001,
    /**
     * Failed to allocate memory.
     *
     * @since 13
     */
    OH_DRAWING_ERROR_ALLOCATION_FAILED = 26200002,
    /**
     * No function matches the input attribute ID.
     *
     * @since 21
     */
    OH_DRAWING_ERROR_ATTRIBUTE_ID_MISMATCH = 26200003,
    /**
     * The input parameter is incorrect. For example, the pointer of the input parameter is null.
     *
     * @since 22
     */
    OH_DRAWING_ERROR_INCORRECT_PARAMETER = 26200004,
    /**
     * File not found. The specified file does not exist or the path is incorrect.
     *
     * @since 23
     */
    OH_DRAWING_ERROR_FILE_NOT_FOUND = 26200005,
    /**
     * Failed to open the file, which is caused by insufficient permissions or I/O issues.
     *
     * @since 23
     */
    OH_DRAWING_ERROR_OPEN_FILE_FAILED = 26200006,
    /**
     * Fails to seek the file. The system cannot reposition the file read pointer.
     *
     * @since 23
     */
    OH_DRAWING_ERROR_FILE_SEEK_FAILED = 26200007,
    /**
     * Failed to obtain the file size. The system cannot obtain the file size information.
     *
     * @since 23
     */
    OH_DRAWING_ERROR_GET_FILE_SIZE_FAILED = 26200008,
    /**
     * Failed to read the file. The file cannot be read completely or contains unreadable data.
     *
     * @since 23
     */
    OH_DRAWING_ERROR_READ_FILE_FAILED = 26200009,
    /**
     * Empty file. The specified font file is empty and does not contain valid data.
     *
     * @since 23
     */
    OH_DRAWING_ERROR_EMPTY_FILE = 26200010,
    /**
     * Corrupted file. The file content is invalid or corrupted, and cannot be parsed.
     *
     * @since 23
     */
    OH_DRAWING_ERROR_FILE_CORRUPTED = 26200011,
} OH_Drawing_ErrorCode;

/**
 * @brief Obtains the error code of the module.
 *
 * @return Returns the error code.
 * @since 12
 * @version 1.0
 */
OH_Drawing_ErrorCode OH_Drawing_ErrorCodeGet();

/**
 * @brief Resets the error code of this module to **OH_DRAWING_SUCCESS**.
 * When a function that does not return an error code fails, the error code obtained through {@link
 * OH_Drawing_ErrorCodeGet} is reset to the corresponding error number. However, it is not reset to
 * **OH_DRAWING_SUCCESS** for a successful operation. By calling this function, you can manually reset the error code to
 * **OH_DRAWING_SUCCESS**, avoiding interference between different functions and simplifying the debugging process.
 *
 * @since 18
 * @version 1.0
 */
void OH_Drawing_ErrorCodeReset(void);
#ifdef __cplusplus
}
#endif
/** @} */
#endif