/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup Native_Bundle
 * @{
 *
 * @brief Describes the Native Bundle.
 *
 * @since 9
 * @version 1.0
 */

/**
 * @file native_interface_bundle.h
 *
 * @brief The file declares the APIs for obtaining the application information, including the bundle name, fingerprint
 * information, and appId.
 *
 * @kit AbilityKit
 * @library libbundle_ndk.z.so
 * @syscap SystemCapability.BundleManager.BundleFramework.Core
 * @since 9
 * @version 1.0
 */
#ifndef FOUNDATION_APPEXECFWK_STANDARD_KITS_APPKIT_NATIVE_BUNDLE_INCLUDE_NATIVE_INTERFACE_BUNDLE_H
#define FOUNDATION_APPEXECFWK_STANDARD_KITS_APPKIT_NATIVE_BUNDLE_INCLUDE_NATIVE_INTERFACE_BUNDLE_H

#include <stdbool.h>
#include <stddef.h>

#include "ability_resource_info.h"
#include "bundle_manager_common.h"

#ifdef __cplusplus
extern "C" {
#endif
/**
 * @brief The struct describes the application information, including the bundle name and fingerprint information.
 *
 * @syscap SystemCapability.BundleManager.BundleFramework.Core
 * @since 9
 */
struct OH_NativeBundle_ApplicationInfo {
    /**
     * Pointer to the bundle name of the application.
     * @syscap SystemCapability.BundleManager.BundleFramework.Core
     * @since 9
     */
    char* bundleName;

    /**
     * Pointer to the fingerprint information of the application. It is generated by calculating the hash value of the
     * signing certificate using the SHA-256 algorithm. This field changes when the used signing certificate changes.
     * @syscap SystemCapability.BundleManager.BundleFramework.Core
     * @since 9
     */
    char* fingerprint;
};

/**
 * @brief The struct describes the elementName information.
 *
 * @since 13
 */
struct OH_NativeBundle_ElementName {
    /**
     * Pointer to the bundle name of the application.
     */
    char* bundleName;
    /**
     * Pointer to the module name.
     */
    char* moduleName;
    /**
     * Pointer to the ability name.
     */
    char* abilityName;
};

/**
 * @brief The struct describes the metadata information.
 *
 * @since 20
 */
typedef struct OH_NativeBundle_Metadata {
    /**
     * @brief Pointer to the name of the metadata.
     *
     */
    char* name;
    /**
     * @brief Pointer to the value of the metadata.
     *
     */
    char* value;
    /**
     * @brief Pointer to the resource linked to the metadata.
     *
     */
    char* resource;
} OH_NativeBundle_Metadata;

/**
 * @brief The struct describes the metadata of a module.
 *
 * @since 20
 */
typedef struct OH_NativeBundle_ModuleMetadata {
    /**
     * @brief Pointer to the module name.
     *
     */
    char* moduleName;
    /**
     * @brief Pointer to an array containing the module's metadata.
     *
     */
    OH_NativeBundle_Metadata* metadataArray;
    /**
     * @brief Number of elements in the metadata array.
     *
     */
    size_t metadataArraySize;
} OH_NativeBundle_ModuleMetadata;

/**
 * @brief The struct describes the application information, including the bundle name and fingerprint information.
 *
 * @since 11
 * @version 1.0
 */
typedef struct OH_NativeBundle_ApplicationInfo OH_NativeBundle_ApplicationInfo;

/**
 * @brief The struct describes the elementName information.
 *
 * @since 13
 * @version 1.0
 */
typedef struct OH_NativeBundle_ElementName OH_NativeBundle_ElementName;

/**
 * @brief Obtains the current application information, including the bundle name and fingerprint information.
 *
 * @return Pointer to the OH_NativeBundle_ApplicationInfo object. If the attribute of the returned object is NULL,
 *     the creation fails. The possible cause is that the application address space is full, causing space
 *     allocation to fail.
 * @since 9
 * @version 1.0
 */
OH_NativeBundle_ApplicationInfo OH_NativeBundle_GetCurrentApplicationInfo();

/**
 * @brief Obtains the appId of the current application. The appId is the unique identifier of an application and is
 * determined by the bundle name and signature information of the application. After using this function, you must
 * manually release the pointer returned to prevent memory leakage.
 *
 * @return Pointer to a new string that indicates the appID. If the returned object is NULL, the creation fails.
 *     <br> The possible cause is that the application address space is full, causing space allocation to fail.
 * @since 11
 * @version 1.0
 */
char* OH_NativeBundle_GetAppId();

/**
 * @brief Obtains the appIdentifier of the current application. The appIdentifier does not change throughout the
 * application lifecycle, including version updates, certificate changes, public and private key changes, and
 * application migration. After using this function, you must manually release the pointer returned to prevent memory
 * leakage.
 *
 * @return Pointer to a new string that indicates the appIdentifier. If the returned object is NULL, the creation
 *     fails. The possible cause is that the application address space is full, causing space allocation to fail.
 * @since 11
 * @version 1.0
 */
char* OH_NativeBundle_GetAppIdentifier();

/**
 * @brief Obtains the mainElement information of the current application, including the bundle name, module name, and
 * ability name. After using this function, you must manually release the pointer returned to prevent memory leakage.
 *
 * @return Pointer to the OH_NativeBundle_ElementName object. If the attribute of the returned object is NULL,
 *     the creation fails. The possible cause is that the application address space is full, causing space
 *     allocation to fail.
 * @since 13
 */
OH_NativeBundle_ElementName OH_NativeBundle_GetMainElementName();

/**
 * @brief Obtains the compatible device type of the current application. It helps you optimize the layout and font
 * size when distributing mobile applications to tablets or 2-in-1 devices. After using this function, you must
 * manually release the pointer returned to prevent memory leakage.
 *
 * @return Pointer to a new string that indicates the compatible device type. If the returned object is NULL, the
 *     creation fails.
 *     <br> The possible cause is that the application address space is full, causing space allocation to fail.
 * @since 14
 * @version 1.0
 */
char* OH_NativeBundle_GetCompatibleDeviceType();

/**
 * @brief Checks whether the current application is in debug mode.
 *
 * @param isDebugMode Pointer to the check result indicating whether the application is in debug mode. **true** if in
 *     debug mode, **false** otherwise.
 * @return Operation result. **true** if the call is successful, **false** otherwise.
 * @since 20
 */
bool OH_NativeBundle_IsDebugMode(bool* isDebugMode);

/**
 * @brief Obtains the module metadata array of the current application. After using this function, you must manually
 * release the pointer returned to prevent memory leakage.
 *
 * @param size Pointer to the size of the module metadata array.
 * @return An array of module metadata. If the returned object is NULL, the retrieval fails.
 *     <br> The possible cause is that the application address space is full, causing space allocation to fail.
 * @since 20
 */
OH_NativeBundle_ModuleMetadata* OH_NativeBundle_GetModuleMetadata(size_t* size);

/**
 * @brief Obtain a list of ability that support opening files in a certain format.
 *
 * @permission ohos.permission.GET_ABILITY_INFO
 * @param fileType Indicates the file type.
 * @param abilityResourceInfo Indicates the ability resource array.
 * @param size Indicates the ability resource array size.
 * @return <ul><li>Returns {@link BUNDLE_MANAGER_ERROR_CODE_NO_ERROR} if the call is successful.</li><li>
 *     Returns {@link BUNDLE_MANAGER_ERROR_CODE_PERMISSION_DENIED} if the caller has no correct permission.</li></ul>
 * @since 21
 */
BundleManager_ErrorCode OH_NativeBundle_GetAbilityResourceInfo(char* fileType,
    OH_NativeBundle_AbilityResourceInfo** abilityResourceInfo, size_t* size);
#ifdef __cplusplus
};
#endif

/** @} */
#endif // FOUNDATION_APPEXECFWK_STANDARD_KITS_APPKIT_NATIVE_BUNDLE_INCLUDE_NATIVE_INTERFACE_BUNDLE_H