/*
 * Copyright (c) 2022-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup HuksKeyApi
 * @{
 *
 * @brief Describes the OpenHarmony Universal KeyStore (HUKS) capabilities, including key management and
 *    cryptography operations, provided for applications.
 *    The keys managed by HUKS can be imported by applications or generated by calling the HUKS APIs.
 *
 * @since 9
 * @version 1.0
 */

/**
 * @file native_huks_api.h
 *
 * @brief 声明用于访问HUKS的API。
 *
 * @library libhuks_ndk.z.so
 * @syscap SystemCapability.Security.Huks.Core
 *
 * @kit UniversalKeystoreKit
 * @since 9
 * @version 1.0
 */

#ifndef NATIVE_HUKS_API_H
#define NATIVE_HUKS_API_H

#include "native_huks_type.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief 获取当前Huks sdk版本号。
 *
 * @param sdkVersion 用于存放获取到的版本信息（字符串格式）。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：sdkVersion或者sdkVersion->data是null，或者sdkVersion->size太小。
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_GetSdkVersion(struct OH_Huks_Blob *sdkVersion);

/**
 * @brief 生成密钥。
 *
 * @param keyAlias 给要生成的密钥的别名，需要保证业务所在进程内唯一，否则会发生覆盖。
 * @param paramSetIn 生成密钥的属性信息的参数集。
 * @param paramSetOut 生成密钥为临时类型时，存放着密钥数据；非临时类型可为空。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数keyAlias、paramSetIn、paramSetOut有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_FILE_OPERATION_FAIL = 12000004 ：删除或者写文件失败。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：基础密钥文件不存在。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL = 12000006 ：加密引擎失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_CALL_SERVICE_FAILED = 12000015 ：连接用户IAM失败。
 *     <br>OH_HUKS_ERR_CODE_DEVICE_PASSWORD_UNSET = 12000016 ：需要设备密码但没有设置。
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001 ：暂不支持该功能。
 *     <br>OH_HUKS_ERR_CODE_KEY_ALREADY_EXIST = 12000017 ：（API 20新增）同名密钥已存在。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_GenerateKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSetIn, struct OH_Huks_ParamSet *paramSetOut);

/**
 * @brief 导入明文密钥。
 *
 * @param keyAlias 待导入密钥的别名，需要保证业务所在进程内唯一，否则会发生覆盖。
 * @param paramSet 待导入密钥的属性参数。
 * @param key 待导入密钥数据，需符合Huks的格式要求，具体见{@link native_huks_type.h}。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数keyAlias、paramSet、key有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_FILE_OPERATION_FAIL = 12000004 ：删除或者写文件失败。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_CALL_SERVICE_FAILED = 12000015 ：连接用户IAM失败。
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001 ：暂不支持该功能。
 *     <br>OH_HUKS_ERR_CODE_KEY_ALREADY_EXIST = 12000017 ：（API 20新增）同名密钥已存在。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_ImportKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet, const struct OH_Huks_Blob *key);

/**
 * @brief 导入密文密钥。
 *
 * @param keyAlias 待导入密钥的别名，需要保证业务所在进程内唯一，否则会发生覆盖。
 * @param wrappingKeyAlias 密钥别名，该对应密钥用于密钥协商出密钥解密待导入密钥。
 * @param paramSet 待导入加密密钥的属性参数。
 * @param wrappedKeyData 需要导入的加密的密钥数据，需要符合Huks定义的格式，具体见{@link OH_Huks_AlgSuite}。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数keyAlias、wrappingKeyAlias、paramSet、wrappedKeyData有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_FILE_OPERATION_FAIL = 12000004 ：删除或者写文件失败。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL = 12000006 ：加密引擎失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_CALL_SERVICE_FAILED = 12000015 ：连接用户IAM失败。
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001 ：暂不支持该功能。
 *     <br>OH_HUKS_ERR_CODE_KEY_ALREADY_EXIST = 12000017 ：（API 20新增）同名密钥已存在。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_ImportWrappedKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_Blob *wrappingKeyAlias, const struct OH_Huks_ParamSet *paramSet,
    const struct OH_Huks_Blob *wrappedKeyData);

/**
 * @brief 导出公钥。
 *
 * @param keyAlias 待导出公钥的密钥别名，应与所用密钥生成时使用的别名相同。
 * @param paramSet 导出公钥需要的属性参数。
 * @param key 存放导出的公钥。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数keyAlias、paramSet、key有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：密钥文件不存在。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001 ：暂不支持该功能。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_ExportPublicKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet, struct OH_Huks_Blob *key);

/**
 * @brief 删除密钥。
 *
 * @param keyAlias 待删除密钥的别名，应与密钥生成时使用的别名相同。
 * @param paramSet 删除密钥需要属性参数（默认传空）。若不指定则默认要删除的密钥存储等级为{@link OH_HUKS_AUTH_STORAGE_LEVEL_CE}。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数keyAlias、paramSet有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：密钥文件不存在。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_DeleteKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet);

/**
 * @brief 获取密钥的属性集。
 *
 * @param keyAlias 要获取参数集的密钥别名。
 * @param paramSetIn 要获取参数集需要的属性TAG（默认传空）。
 * @param paramSetOut 获取到的输出参数集。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数keyAlias、paramSetIn、paramSetOut有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：密钥文件不存在。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001 ：暂不支持该功能。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_GetKeyItemParamSet(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSetIn, struct OH_Huks_ParamSet *paramSetOut);

/**
 * @brief 判断密钥是否存在。
 *
 * @param keyAlias 要查找的密钥的别名。
 * @param paramSet 查询密钥需要的属性TAG（默认传空）。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数keyAlias、paramSet有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：密钥文件不存在。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_IsKeyItemExist(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet);

/**
 * @brief 获取密钥证书链。该API仅面向系统应用开放。
 *
 * @permission ohos.permission.ATTEST_KEY
 * @param keyAlias 要获取证书的密钥的别名。
 * @param paramSet 获取密钥证书需要的参数。
 * @param certChain 存放输出的密钥证书链。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数keyAlias、paramSet、certChain有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：密钥文件不存在。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL = 12000006 ：加密引擎失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001 ：暂不支持该功能。
 *     <br>OH_HUKS_ERR_CODE_PERMISSION_FAIL = 201 ：权限检查失败，请先申请请求权限。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_AttestKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet, struct OH_Huks_CertChain *certChain);

/**
 * @brief 获取密钥证书链。
 * <br>这是一个涉及网络的耗时接口，调用方可以通过异步线程获取证书链。
 *
 * @param keyAlias 要获取证书的密钥的别名。
 * @param paramSet 获取密钥证书需要的参数。
 * @param certChain 存放输出的密钥证书链。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数keyAlias、paramSet、certChain有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：密钥文件不存在。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL = 12000006 ：加密引擎失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001 ：暂不支持该功能。
 *     <br>OH_HUKS_ERR_CODE_PERMISSION_FAIL = 201 ：权限检查失败，请先申请请求权限。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 11
 * @version 1.0
 * @note this is a networking duration interface caller need to get the certChain in asynchronous thread
 */
struct OH_Huks_Result OH_Huks_AnonAttestKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet, struct OH_Huks_CertChain *certChain);

/**
 * @brief 初始化密钥会话接口，并获取一个句柄（必选）和挑战值（可选）。
 *
 * @param keyAlias 操作的密钥的别名。
 * @param paramSet 初始化操作的密钥参数集合。
 * @param handle 密钥会话的句柄，后续其他操作时传入该句柄，包括{@link OH_Huks_UpdateSession}，{@link OH_Huks_FinishSession}，
 *     {@link OH_Huks_AbortSession}。
 * @param token 存放安全访问控制时传回的token。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数 keyAlias、paramSet、handle、token有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：密钥文件不存在。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_SESSION_LIMIT = 12000010 ：已达最大会话限制。
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL = 12000006 ：加密引擎失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001 ：暂不支持该功能。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 22新增）指定的aead长度无效或者通过访问群组标签指定的群组名无效。
 *     <br>OH_HUKS_ERR_CODE_EXTERNAL_MODULE = 12000020 ：（API 22新增）提供者或Ukey内部执行失败。
 *     <br>OH_HUKS_ERR_CODE_PIN_LOCKED = 12000021 ：（API 22新增）PIN码被锁定。
 *     <br>OH_HUKS_ERR_CODE_PIN_NO_AUTH = 12000023 ：（API 22新增）PIN码未认证通过。
 *     <br>OH_HUKS_ERR_CODE_BUSY = 12000024 ：（API 22新增）提供者或Ukey中的资源正在被使用。
 * @since 9
 * @version 1.0
 * @see OH_Huks_UpdateSession
 * @see OH_Huks_FinishSession
 * @see OH_Huks_AbortSession
 */
struct OH_Huks_Result OH_Huks_InitSession(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet, struct OH_Huks_Blob *handle, struct OH_Huks_Blob *token);

/**
 * @brief 分段添加密钥操作的数据并进行相应的密钥操作，输出处理数据。
 *
 * @param handle 密钥会话句柄，通过{@link OH_Huks_InitSession}接口生成。
 * @param paramSet 密钥操作对应的输入参数集。
 * @param inData 要处理的输入数据，如果数据过大，可分片多次调用。
 * @param outData 经过对应的密钥操作后输出的数据。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数handle、paramSet、inData、outData有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：密钥文件不存在，或handle不存在。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_CREDENTIAL_NOT_EXIST = 12000013 ：证书不存在。
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL = 12000006 ：加密引擎失败。
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_VERIFY_FAILED = 12000008 ：认证令牌校验失败。
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_PERMANENTLY_INVALIDATED = 12000007 ：认证令牌信息校验失败。
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_TIME_OUT = 12000009 ：认证令牌超时。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_DEVICE_PASSWORD_UNSET = 12000016 ：需要设备密码但没有设置。
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001 ：暂不支持该功能。
 *     <br>OH_HUKS_ERR_CODE_EXTERNAL_MODULE = 12000020 ：（API 22新增）提供者或Ukey内部执行失败。
 *     <br>OH_HUKS_ERR_CODE_PIN_LOCKED = 12000021 ：（API 22新增）PIN码被锁定。
 *     <br>OH_HUKS_ERR_CODE_PIN_NO_AUTH = 12000023 ：（API 22新增）PIN码未认证通过。
 *     <br>OH_HUKS_ERR_CODE_BUSY = 12000024 ：（API 22新增）提供者或Ukey中的资源正在被使用。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 * @see OH_Huks_InitSession
 * @see OH_Huks_FinishSession
 * @see OH_Huks_AbortSession
 */
struct OH_Huks_Result OH_Huks_UpdateSession(const struct OH_Huks_Blob *handle,
    const struct OH_Huks_ParamSet *paramSet, const struct OH_Huks_Blob *inData, struct OH_Huks_Blob *outData);

/**
 * @brief 结束密钥会话并进行相应的密钥操作，输出处理数据。
 *
 * @param handle 密钥会话句柄，通过{@link OH_Huks_InitSession}接口生成。
 * @param paramSet 密钥操作对应的输入参数集。
 * @param inData 要处理的输入数据。
 * @param outData 经过对应的密钥操作后输出的数据。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数handle、paramSet、inData、outData有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：密钥文件不存在，或handle不存在。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_CREDENTIAL_NOT_EXIST = 12000013 ：证书不存在。
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL = 12000006 ：加密引擎失败。
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_VERIFY_FAILED = 12000008 ：认证令牌校验失败。
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_PERMANENTLY_INVALIDATED = 12000007 ：认证令牌信息校验失败。
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_TIME_OUT = 12000009 ：认证令牌超时。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_DEVICE_PASSWORD_UNSET = 12000016 ：需要设备密码但没有设置。
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED = 12000001 ：暂不支持该功能。
 *     <br>OH_HUKS_ERR_CODE_KEY_ALREADY_EXIST = 12000017 ：（API 20新增）同名密钥已存在。
 *     <br>OH_HUKS_ERR_CODE_EXTERNAL_MODULE = 12000020 ：（API 22新增）提供者或Ukey内部执行失败。
 *     <br>OH_HUKS_ERR_CODE_PIN_LOCKED = 12000021 ：（API 22新增）PIN码被锁定。
 *     <br>OH_HUKS_ERR_CODE_PIN_NO_AUTH = 12000023 ：（API 22新增）PIN码未认证通过。
 *     <br>OH_HUKS_ERR_CODE_BUSY = 12000024 ：（API 22新增）提供者或Ukey中的资源正在被使用。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 * @see OH_Huks_InitSession
 * @see OH_Huks_UpdateSession
 * @see OH_Huks_AbortSession
 */
struct OH_Huks_Result OH_Huks_FinishSession(const struct OH_Huks_Blob *handle,
    const struct OH_Huks_ParamSet *paramSet, const struct OH_Huks_Blob *inData, struct OH_Huks_Blob *outData);

/**
 * @brief 取消密钥会话。
 *
 * @param handle 密钥会话句柄，通过{@link OH_Huks_InitSession}接口生成。
 * @param paramSet 取消密钥会话需要的输入参数集（默认传空）。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数handle、paramSet、inData、outData有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT = 12000003 ：密钥参数无效。
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST = 12000011 ：密钥文件不存在，或handle不存在。
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT = 12000002 ：获取密钥参数失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_CREDENTIAL_NOT_EXIST = 12000013 ：证书不存在。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_EXTERNAL_MODULE = 12000020 ：（API 22新增）提供者或Ukey内部执行失败。
 *     <br>OH_HUKS_ERR_CODE_BUSY = 12000024 ：（API 22新增）提供者或Ukey中的资源正在被使用。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 9
 * @version 1.0
 * @see OH_Huks_InitSession
 * @see OH_Huks_UpdateSession
 * @see OH_Huks_FinishSession
 */
struct OH_Huks_Result OH_Huks_AbortSession(const struct OH_Huks_Blob *handle,
    const struct OH_Huks_ParamSet *paramSet);

/**
 * @brief 获取密钥别名集。
 *
 * @param paramSet 获取密钥别名集需要的输入参数集（默认传空）。
 * @param outData 经过对应的密钥操作后输出的数据。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT = 401 ：参数paramSet、outData有一个无效。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：（API 23新增）通过访问群组标签指定的群组名无效。
 * @since 20
 */
struct OH_Huks_Result OH_Huks_ListAliases(const struct OH_Huks_ParamSet *paramSet,
    struct OH_Huks_KeyAliasSet **outData);

/**
 * @brief 导出由特定密钥加密的封装密钥。
 *
 * @param keyAlias 表示要导出的密钥别名。
 * @param paramSet 表示加密导出密钥的参数集。
 * @param wrappedKey 表示要导出的封装好的密钥。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_NOT_SUPPORTED_API = 801 ：接口不支持。
 *     <br>OH_HUKS_ERR_CODE_FILE_OPERATION_FAIL = 12000004 ：删除或者写文件失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL = 12000011 ：密钥文件不存在。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：密钥别名、参数集或者封装密钥不合法。
 * @since 20
 */
struct OH_Huks_Result OH_Huks_WrapKey(const struct OH_Huks_Blob *keyAlias, const struct OH_Huks_ParamSet *paramSet,
    struct OH_Huks_Blob *wrappedKey);

/**
 * @brief 导入由特定密钥加密的封装密钥。
 *
 * @param keyAlias 表示要导入的密钥别名。在服务进程中，别名必须唯一。否则，密钥将被覆盖。
 * @param paramSet 表示加密导入密钥的参数集。
 * @param wrappedKey 表示要导入的封装好的密钥。
 * @return 可能的返回码（errorCode）：
 *     <br>OH_HUKS_SUCCESS = 0 ：操作成功。
 *     <br>OH_HUKS_ERR_CODE_NOT_SUPPORTED_API = 801 ：接口不支持。
 *     <br>OH_HUKS_ERR_CODE_FILE_OPERATION_FAIL = 12000004 ：删除或者写文件失败。
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL = 12000005 ：IPC通信失败。
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR = 12000012 ：设备环境或输入参数异常。
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY = 12000014 ：内存不足。
 *     <br>OH_HUKS_ERR_CODE_CALL_SERVICE_FAILED = 12000015 ：连接用户IAM失败。
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT = 12000018 ：密钥别名、参数集或者封装密钥不合法。
 * @since 20
 */
struct OH_Huks_Result OH_Huks_UnwrapKey(const struct OH_Huks_Blob *keyAlias, const struct OH_Huks_ParamSet *paramSet,
    struct OH_Huks_Blob *wrappedKey);

#ifdef __cplusplus
}
#endif

/** @} */
#endif /* NATIVE_HUKS_API_H */
