/*
 * Copyright (c) 2022-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup HuksKeyApi
 * @{
 *
 * @brief Describes the OpenHarmony Universal KeyStore (HUKS) capabilities, including key management and
 *    cryptography operations, provided for applications.
 *    The keys managed by HUKS can be imported by applications or generated by calling the HUKS APIs.
 *
 * @since 9
 * @version 1.0
 */

/**
 * @file native_huks_api.h
 *
 * @brief Declares the APIs used to access the HUKS.
 *
 * @library libhuks_ndk.z.so
 * @syscap SystemCapability.Security.Huks.Core
 *
 * @kit UniversalKeystoreKit
 * @since 9
 * @version 1.0
 */
#ifndef NATIVE_HUKS_API_H
#define NATIVE_HUKS_API_H
#include "native_huks_type.h"
#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Obtains the current HUKS SDK version.
 *
 * @param sdkVersion Pointer to the SDK version (string) obtained.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: The value of **sdkVersion** or **sdkVersion->data** is **null**,
 *      or the value of **sdkVersion->size** is too small.
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_GetSdkVersion(struct OH_Huks_Blob *sdkVersion);

/**
 * @brief Generates a key.
 *
 * @param keyAlias Pointer to the alias of the key to generate. The alias must be unique in the process of the service.
 * @param paramSetIn Pointer to the parameters for generating the key.
 * @param paramSetOut Pointer to a temporary key generated. If the generated key is not a temporary key, this parameter
 *     is a null pointer.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **keyAlias**, **paramSetIn**, or **paramSetOut** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_FILE_OPERATION_FAIL 12000004: Failed to delete or write the file.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file does not exist.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL 12000006: The encryption engine failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_CALL_SERVICE_FAILED 12000015: Failed to connect to the user IAM.
 *     <br>OH_HUKS_ERR_CODE_DEVICE_PASSWORD_UNSET 12000016: No device password is set.
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED 12000001: This feature is not supported currently.
 *     <br>OH_HUKS_ERR_CODE_KEY_ALREADY_EXIST 12000017: A key with the same name already exists. (This error code
 *     is added in API version 20.)
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_GenerateKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSetIn, struct OH_Huks_ParamSet *paramSetOut);

/**
 * @brief Imports a key in plaintext.
 *
 * @param keyAlias Pointer to the alias of the key to import. The alias must be unique in the process of the service.
 * @param paramSet Pointer to the properties of the key to import.
 * @param key Pointer to the data of the key to import, complying with the format requirements of HUKS. For details,
 *     see {@link native_huks_type.h}.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **keyAlias**, **paramSet**, or **key** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_FILE_OPERATION_FAIL 12000004: Failed to delete or write the file.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_CALL_SERVICE_FAILED 12000015: Failed to connect to the user IAM.
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED 12000001: This feature is not supported currently.
 *     <br>OH_HUKS_ERR_CODE_KEY_ALREADY_EXIST 12000017: A key with the same name already exists. (This error code
 *     is added in API version 20.)
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_ImportKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet, const struct OH_Huks_Blob *key);

/**
 * @brief Imports a key in ciphertext.
 *
 * @param keyAlias Pointer to the alias of the key to import. The alias must be unique in the process of the service.
 * @param wrappingKeyAlias Pointer to the alias of the key used for key agreement, which generates a shared secret to
 *     decrypt the key to import.
 * @param paramSet Pointer to the parameters for importing the key in ciphertext.
 * @param wrappedKeyData Pointer to the data of the key to import, complying with the format requirements of HUKS. For
 *     details, see {@link OH_Huks_AlgSuite}.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **keyAlias**, **wrappingKeyAlias**, **paramSet**, or **
 *     wrappedKeyData** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_FILE_OPERATION_FAIL 12000004: Failed to delete or write the file.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL 12000006: The encryption engine failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_CALL_SERVICE_FAILED 12000015: Failed to connect to the user IAM.
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED 12000001: This feature is not supported currently.
 *     <br>OH_HUKS_ERR_CODE_KEY_ALREADY_EXIST 12000017: A key with the same name already exists. (This error code
 *     is added in API version 20.)
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_ImportWrappedKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_Blob *wrappingKeyAlias, const struct OH_Huks_ParamSet *paramSet,
    const struct OH_Huks_Blob *wrappedKeyData);

/**
 * @brief Exports the public key.
 *
 * @param keyAlias Pointer to the alias of the public key to export. It must be the same as the alias used for
 *     generating the key.
 * @param paramSet Pointer to the parameters for exporting the public key.
 * @param key Pointer to the public key exported.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **keyAlias**, **paramSet**, or **key** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file does not exist.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED 12000001: This feature is not supported currently.
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_ExportPublicKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet, struct OH_Huks_Blob *key);

/**
 * @brief Deletes a key.
 *
 * @param keyAlias Pointer to the alias of the key to delete. It must be the same as the alias used for generating the
 *     key.
 * @param paramSet Pointer to the parameters for deleting the key. By default, this parameter is a null pointer. The
 *     default key storage level is {@link OH_HUKS_AUTH_STORAGE_LEVEL_CE}.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **keyAlias** or **paramSet** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file does not exist.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_DeleteKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet);

/**
 * @brief Obtains the properties of a key.
 *
 * @param keyAlias Pointer to the alias of the target key.
 * @param paramSetIn Pointer to the tag required for obtaining the properties. By default, this parameter is a null
 *     pointer.
 * @param paramSetOut Pointer to the key properties obtained.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **keyAlias**, **paramSetIn**, or **paramSetOut** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file does not exist.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED 12000001: This feature is not supported currently.
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_GetKeyItemParamSet(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSetIn, struct OH_Huks_ParamSet *paramSetOut);

/**
 * @brief Checks whether a key exists.
 *
 * @param keyAlias Pointer to the alias of the key to check.
 * @param paramSet Pointer to the parameters for checking the key. By default, this parameter is a null pointer.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **keyAlias** or **paramSet** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file does not exist.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_IsKeyItemExist(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet);

/**
 * @brief Obtains the certificate chain of a key. This API is open only to system applications.
 *
 * @permission ohos.permission.ATTEST_KEY
 * @param keyAlias Pointer to the alias of the target key.
 * @param paramSet Pointer to the parameters for obtaining the certificate chain.
 * @param certChain Pointer to the certificate chain obtained.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **keyAlias**, **paramSet**, or **certChain** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file does not exist.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL 12000006: The encryption engine failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED 12000001: This feature is not supported currently.
 *     <br>OH_HUKS_ERR_CODE_PERMISSION_FAIL 201: Permission check failed. Request the permission first.
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 */
struct OH_Huks_Result OH_Huks_AttestKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet, struct OH_Huks_CertChain *certChain);

/**
 * @brief Obtains the certificate chain of a key.
 * <br>This function involves time-consuming network operation. The caller can obtain the certificate chain through an
 * asynchronous thread.
 *
 * @param keyAlias Pointer to the alias of the target key.
 * @param paramSet Pointer to the parameters for obtaining the certificate chain.
 * @param certChain Pointer to the certificate chain obtained.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **keyAlias**, **paramSet**, or **certChain** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file does not exist.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL 12000006: The encryption engine failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED 12000001: This feature is not supported currently.
 *     <br>OH_HUKS_ERR_CODE_PERMISSION_FAIL 201: Permission check failed. Request the permission first.
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 11
 * @version 1.0
 * @note this is a networking duration interface caller need to get the certChain in asynchronous thread
 */
struct OH_Huks_Result OH_Huks_AnonAttestKeyItem(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet, struct OH_Huks_CertChain *certChain);

/**
 * @brief Initializes a key session. This function returns a session handle (mandatory) and a challenge value (optional)
 * .
 *
 * @param keyAlias Pointer to the alias of the key to be operated.
 * @param paramSet Pointer to the parameters for the initialization operation.
 * @param handle Pointer to the handle of the key session. This handle is required for subsequent operations of the
 *     same key, including {@link OH_Huks_UpdateSession}, {@link OH_Huks_FinishSession} and
 *     {@link OH_Huks_AbortSession}.
 * @param token Pointer to the token used for key access control.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **keyAlias**, **paramSet**, **handle**, or **token** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file does not exist.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_SESSION_LIMIT 12000010: Hit the session limit.
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL 12000006: The encryption engine failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED 12000001: This feature is not supported currently.
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The specified AEAD length is invalid or the group name
 *     specified by accessing the group tag is invalid. (This error code is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_EXTERNAL_MODULE 12000020: The provider or Ukey internal execution fails. (This error
 *     code is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_PIN_LOCKED 12000021: The PIN is locked. (This error code is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_PIN_NO_AUTH 12000023: The PIN authentication fails. (This error code is added in API
 *     version 22.)
 *     <br>OH_HUKS_ERR_CODE_BUSY 12000024: The resource in the provider or Ukey is being used. (This error code
 *     is added in API version 22.)
 * @since 9
 * @version 1.0
 * @see OH_Huks_UpdateSession
 * @see OH_Huks_FinishSession
 * @see OH_Huks_AbortSession
 */
struct OH_Huks_Result OH_Huks_InitSession(const struct OH_Huks_Blob *keyAlias,
    const struct OH_Huks_ParamSet *paramSet, struct OH_Huks_Blob *handle, struct OH_Huks_Blob *token);

/**
 * @brief Adds data by segment for the key operation, performs the related key operation, and outputs the processed
 * data.
 *
 * @param handle Pointer to the key session handle, which is returned by {@link OH_Huks_InitSession}.
 * @param paramSet Pointer to the parameters required for the key operation.
 * @param inData Pointer to the data to be processed. If there is a large amount of data to be processed, you can call
 *     this function multiple times to process data by segment.
 * @param outData Pointer to the output data.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **handle**, **paramSet**, **inData**, or **outData** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file or the handle does not exist.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_CREDENTIAL_NOT_EXIST 12000013: The certificate does not exist.
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL 12000006: The encryption engine failed.
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_VERIFY_FAILED 12000008: Failed to verify the access token.
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_PERMANENTLY_INVALIDATED 12000007: Failed to verify the access token
 *     information.
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_TIME_OUT 12000009: The verification of the access token times out.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_DEVICE_PASSWORD_UNSET 12000016: No device password is set.
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED 12000001: This feature is not supported currently.
 *     <br>OH_HUKS_ERR_CODE_EXTERNAL_MODULE 12000020: The provider or Ukey internal execution fails. (This error
 *     code is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_PIN_LOCKED 12000021: The PIN is locked. (This error code is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_PIN_NO_AUTH 12000023: The PIN authentication fails. (This error code is added in API
 *     version 22.)
 *     <br>OH_HUKS_ERR_CODE_BUSY 12000024: The resource in the provider or Ukey is being used. (This error code
 *     is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 * @see OH_Huks_InitSession
 * @see OH_Huks_FinishSession
 * @see OH_Huks_AbortSession
 */
struct OH_Huks_Result OH_Huks_UpdateSession(const struct OH_Huks_Blob *handle,
    const struct OH_Huks_ParamSet *paramSet, const struct OH_Huks_Blob *inData, struct OH_Huks_Blob *outData);

/**
 * @brief Finishes a key session.
 *
 * @param handle Pointer to the key session handle, which is returned by {@link OH_Huks_InitSession}.
 * @param paramSet Pointer to the parameters required for the key operation.
 * @param inData Pointer to the data to be passed in.
 * @param outData Pointer to the output data.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **handle**, **paramSet**, **inData**, or **outData** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file or the handle does not exist.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_CREDENTIAL_NOT_EXIST 12000013: The certificate does not exist.
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL 12000006: The encryption engine failed.
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_VERIFY_FAILED 12000008: Failed to verify the access token.
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_PERMANENTLY_INVALIDATED 12000007: Failed to verify the access token
 *     information.
 *     <br>OH_HUKS_ERR_CODE_KEY_AUTH_TIME_OUT 12000009: The verification of the access token times out.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_DEVICE_PASSWORD_UNSET 12000016: No device password is set.
 *     <br>OH_HUKS_ERR_CODE_FEATURE_NOT_SUPPORTED 12000001: This feature is not supported currently.
 *     <br>OH_HUKS_ERR_CODE_KEY_ALREADY_EXIST 12000017: A key with the same name already exists. (This error code
 *     is added in API version 20.)
 *     <br>OH_HUKS_ERR_CODE_EXTERNAL_MODULE 12000020: The provider or Ukey internal execution fails. (This error
 *     code is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_PIN_LOCKED 12000021: The PIN is locked. (This error code is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_PIN_NO_AUTH 12000023: The PIN authentication fails. (This error code is added in API
 *     version 22.)
 *     <br>OH_HUKS_ERR_CODE_BUSY 12000024: The resource in the provider or Ukey is being used. (This error code
 *     is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 * @see OH_Huks_InitSession
 * @see OH_Huks_UpdateSession
 * @see OH_Huks_AbortSession
 */
struct OH_Huks_Result OH_Huks_FinishSession(const struct OH_Huks_Blob *handle,
    const struct OH_Huks_ParamSet *paramSet, const struct OH_Huks_Blob *inData, struct OH_Huks_Blob *outData);

/**
 * @brief Aborts a key session.
 *
 * @param handle Pointer to the key session handle, which is returned by {@link OH_Huks_InitSession}.
 * @param paramSet Pointer to the parameters for aborting the key session. By default, this parameter is a null pointer.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **handle**, **paramSet**, **inData**, or **outData** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INVALID_CRYPTO_ALG_ARGUMENT 12000003: Invalid key parameter.
 *     <br>OH_HUKS_ERR_CODE_ITEM_NOT_EXIST 12000011: The key file or the handle does not exist.
 *     <br>OH_HUKS_ERR_CODE_MISSING_CRYPTO_ALG_ARGUMENT 12000002: Failed to obtain key arguments.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_CREDENTIAL_NOT_EXIST 12000013: The certificate does not exist.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_EXTERNAL_MODULE 12000020: The provider or Ukey internal execution fails. (This error
 *     code is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_BUSY 12000024: The resource in the provider or Ukey is being used. (This error code
 *     is added in API version 22.)
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 9
 * @version 1.0
 * @see OH_Huks_InitSession
 * @see OH_Huks_UpdateSession
 * @see OH_Huks_FinishSession
 */
struct OH_Huks_Result OH_Huks_AbortSession(const struct OH_Huks_Blob *handle,
    const struct OH_Huks_ParamSet *paramSet);

/**
 * @brief Obtains the key alias set.
 *
 * @param paramSet Pointer to the parameters for obtaining the key alias set. By default, this parameter is a null
 *     pointer.
 * @param outData Pointer to the output data.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_ILLEGAL_ARGUMENT 401: **paramSet** or **outData** is invalid.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The group name specified by accessing the group tag is
 *     invalid. (This error code is added in API version 23.)
 * @since 20
 */
struct OH_Huks_Result OH_Huks_ListAliases(const struct OH_Huks_ParamSet *paramSet,
    struct OH_Huks_KeyAliasSet **outData);

/**
 * @brief Exports a wrapped key.
 *
 * @param keyAlias Pointer to the alias of the key to export.
 * @param paramSet Pointer to the parameters for encrypting the exported key.
 * @param wrappedKey Pointer to the wrapped key to export.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_NOT_SUPPORTED_API 801: The API is not supported.
 *     <br>OH_HUKS_ERR_CODE_FILE_OPERATION_FAIL 12000004: Failed to delete or write the file.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_CRYPTO_FAIL 12000011: The key file does not exist.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The key alias, parameter set, or wrapped key is invalid.
 * @since 20
 */
struct OH_Huks_Result OH_Huks_WrapKey(const struct OH_Huks_Blob *keyAlias, const struct OH_Huks_ParamSet *paramSet,
    struct OH_Huks_Blob *wrappedKey);

/**
 * @brief Imports a wrapped key.
 *
 * @param keyAlias Pointer to the alias of the key to import. The alias must be unique in the service process.
 *     Otherwise, the key will be overwritten.
 * @param paramSet Pointer to the parameters for encrypting the imported key.
 * @param wrappedKey Pointer to the wrapped key to import.
 * @return {@link OH_Huks_ErrCode}:
 *     <br>OH_HUKS_SUCCESS 0: Operation successful.
 *     <br>OH_HUKS_ERR_CODE_NOT_SUPPORTED_API 801: The API is not supported.
 *     <br>OH_HUKS_ERR_CODE_FILE_OPERATION_FAIL 12000004: Failed to delete or write the file.
 *     <br>OH_HUKS_ERR_CODE_COMMUNICATION_FAIL 12000005: IPC communication failed.
 *     <br>OH_HUKS_ERR_CODE_INTERNAL_ERROR 12000012: The device environment is abnormal or input parameters are
 *     incorrect.
 *     <br>OH_HUKS_ERR_CODE_INSUFFICIENT_MEMORY 12000014: Insufficient memory.
 *     <br>OH_HUKS_ERR_CODE_CALL_SERVICE_FAILED 12000015: Failed to connect to the user IAM.
 *     <br>OH_HUKS_ERR_CODE_INVALID_ARGUMENT 12000018: The key alias, parameter set, or wrapped key is invalid.
 * @since 20
 */
struct OH_Huks_Result OH_Huks_UnwrapKey(const struct OH_Huks_Blob *keyAlias, const struct OH_Huks_ParamSet *paramSet,
    struct OH_Huks_Blob *wrappedKey);
#ifdef __cplusplus
}
#endif

/** @} */
#endif /* NATIVE_HUKS_API_H */