/*
 * Copyright (C) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup AudioCodec
 * @{
 *
 * @brief The AudioCodec module provides functions for audio encoding and decoding.
 *
 * @syscap SystemCapability.Multimedia.Media.AudioCodec
 * @since 11
 */

/**
 * @file native_avcodec_audiocodec.h
 *
 * @brief The file declares the native APIs used for audio encoding and decoding.
 *
 * @kit AVCodecKit
 * @library libnative_media_acodec.so
 * @syscap SystemCapability.Multimedia.Media.AudioCodec
 * @since 11
 */

#ifndef NATIVE_AVCODEC_AUDIOCODEC_H
#define NATIVE_AVCODEC_AUDIOCODEC_H

#include <stdint.h>
#include <stdio.h>
#include "native_avcodec_base.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief The struct describes a media key session.
 *
 * @since 12
 */
typedef struct MediaKeySession MediaKeySession;

/**
 * @brief Creates an audio codec instance based on a MIME type. This function is recommended in most cases.
 *
 * @param mime Pointer to a string that describes the MIME type. For details, see {@link AVCODEC_MIMETYPE}.
 * @param isEncoder The value **true** means to create an encoder, and **false** means to create a decoder.
 * @return Pointer to an OH_AVCodec instance.
 * @since 11
 */
OH_AVCodec *OH_AudioCodec_CreateByMime(const char *mime, bool isEncoder);

/**
 * @brief Creates an audio codec instance based on a codec name. To use this function, you must know the exact name of
 * the codec, which can be obtained by calling {@link OH_AVCapability_GetName}.
 *
 * @param name Pointer to an audio codec name.
 * @return Pointer to an OH_AVCodec instance.
 * @since 11
 */
OH_AVCodec *OH_AudioCodec_CreateByName(const char *name);

/**
 * @brief Clears the internal resources of an audio codec and destroys the codec instance. Do not repeatedly destroy
 * the instance. Otherwise, the program may crash.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: The OH_AVCodec instance is nullptr or invalid.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 *     <br>{@link AV_ERR_NO_MEMORY}: Internal resources have been released.
 *     <br>{@link AV_ERR_UNKNOWN}: An internal error occurs. You are advised to check logs.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_Destroy(OH_AVCodec *codec);

/**
 * @brief Sets an asynchronous callback so that your application can respond to events generated by an audio codec.
 * This function must be called prior to **Prepare**.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param callback Set of all callback functions.
 * @param userData User-specific data.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: An input parameter is nullptr or invalid.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_RegisterCallback(OH_AVCodec *codec, OH_AVCodecCallback callback, void *userData);

/**
 * @brief Configures the audio description. The audio codec is usually configured based on the audio description. This
 * function must be called prior to **Prepare**.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param format Pointer to an OH_AVFormat instance, which provides the description information about the audio track
 *     to be encoded or decoded.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: An input parameter is nullptr or invalid.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 *     <br>{@link AV_ERR_OPERATE_NOT_PERMIT}: The operation is not allowed. This may be because of incorrect state or
 *     unsupported operation.
 *     <br>{@link AV_ERR_UNKNOWN}: An internal error occurs. You are advised to check logs.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_Configure(OH_AVCodec *codec, const OH_AVFormat *format);

/**
 * @brief Prepares internal resources for an audio codec. This function must be called after **Configure**.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: The OH_AVCodec instance is nullptr or invalid.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 *     <br>{@link AV_ERR_OPERATE_NOT_PERMIT}: The operation is not allowed. This may be because of incorrect state or
 *     unsupported operation.
 *     <br>{@link AV_ERR_UNKNOWN}: An internal error occurs. You are advised to check logs.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_Prepare(OH_AVCodec *codec);

/**
 * @brief Starts an audio codec after it is prepared successfully. After being started, the codec starts to report the
 * **OH_AVCodecOnNeedInputBuffer** event.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: The OH_AVCodec instance is nullptr or invalid.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 *     <br>{@link AV_ERR_OPERATE_NOT_PERMIT}: The operation is not allowed. This may be because of incorrect state or
 *     unsupported operation.
 *     <br>{@link AV_ERR_UNKNOWN}: An internal error occurs. You are advised to check logs.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_Start(OH_AVCodec *codec);

/**
 * @brief Stops an audio codec. After the codec is stopped, you can call **Start** to start it again. If you have
 * passed specific data in the previous **Start** for the codec, you must pass it again.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: The OH_AVCodec instance is nullptr or invalid.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 *     <br>{@link AV_ERR_OPERATE_NOT_PERMIT}: The operation is not allowed. This may be because of incorrect state or
 *     unsupported operation.
 *     <br>{@link AV_ERR_UNKNOWN}: An internal error occurs. You are advised to check logs.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_Stop(OH_AVCodec *codec);

/**
 * @brief Clears the input and output data in the internal buffer of an audio codec. This function invalidates the
 * indexes of all buffers previously reported through the asynchronous callback. Therefore, before calling this
 * function, ensure that the buffers with the specified indexes are no longer required.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: The OH_AVCodec instance is nullptr or invalid.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 *     <br>{@link AV_ERR_OPERATE_NOT_PERMIT}: The operation is not allowed. This may be because of incorrect state or
 *     unsupported operation.
 *     <br>{@link AV_ERR_UNKNOWN}: An internal error occurs. You are advised to check logs.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_Flush(OH_AVCodec *codec);

/**
 * @brief Resets an audio codec. The configured parameters and input and output data are cleared.
 *
 * To continue encoding or decoding, you must call **Configure** to configure the codec again.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: The OH_AVCodec instance is nullptr or invalid.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_Reset(OH_AVCodec *codec);

/**
 * @brief Obtains the OH_AVFormat information about the output data of an audio codec.
 *
 * You must call {@link OH_AVFormat_Destroy} to manually release the OH_AVFormat instance in the return value.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @return Handle to an OH_AVFormat instance. The lifecycle of this instance is refreshed when
 *     {@link OH_AudioCodec_GetOutputDescription} is called again and destroyed when the OH_AVCodec instance is
 *     destroyed.
 * @since 11
 */
OH_AVFormat *OH_AudioCodec_GetOutputDescription(OH_AVCodec *codec);

/**
 * @brief Sets dynamic parameters for an audio codec.
 *
 * This function can be called only after the codec is started. Incorrect parameter settings may cause encoding or
 * decoding failure.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param format Handle to an OH_AVFormat instance.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: An input parameter is nullptr or invalid.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 *     <br>{@link AV_ERR_OPERATE_NOT_PERMIT}: The operation is not allowed. This may be because of incorrect state or
 *     unsupported operation.
 *     <br>{@link AV_ERR_UNKNOWN}: An internal error occurs. You are advised to check logs.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_SetParameter(OH_AVCodec *codec, const OH_AVFormat *format);

/**
 * @brief Notifies the audio codec that the input data has been written to the buffer identified by **index**.
 *
 * The {@link OH_AVCodecOnNeedInputBuffer} callback reports the available input buffer and the index.
 *
 * After being pushed to the codec, a buffer is not accessible until the buffer with the same index is reported
 * again through the {@link OH_AVCodecOnNeedInputBuffer} callback.
 *
 * In addition, some codecs require the input of codec-specific data to initialize the encoding or decoding process.
 *
 * Note: If the return value is **AV_ERR_UNKNOWN**, the call does not take effect, and the input buffer is still in
 * the unprocessed state. You need to handle the error according to the specific error code and then call **
 * OH_AudioCodec_PushInputBuffer**.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param index Index of the {@link OH_AVCodecOnNeedInputBuffer} callback.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: The input index is used or invalid. Use the index returned by the
 *     {@link OH_AVCodecOnNeedInputBuffer} callback.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec state is incorrect.
 *     Before calling **OH_AudioCodec_PushInputBuffer**, ensure that {@link OH_AudioCodec_Configure},
 *     {@link OH_AudioCodec_Prepare}, and {@link OH_AudioCodec_Start} are successfully called in sequence.
 *     <br>{@link AV_ERR_UNKNOWN}: The input buffer size is invalid. Ensure that the buffer size and flags are
 *     correctly set.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_PushInputBuffer(OH_AVCodec *codec, uint32_t index);

/**
 * @brief Frees an output buffer of an audio codec. You need to call this function to release the output buffer in a
 * timely manner. Otherwise, the encoding or decoding process is blocked.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param index Index of the {@link OH_AVCodecOnNewOutputBuffer} callback.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: An input parameter is nullptr or invalid. The buffer index is obtained from
 *     {@link OH_AVCodecOnNewOutputBuffer}.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 *     <br>{@link AV_ERR_OPERATE_NOT_PERMIT}: The operation is not allowed. This may be because of incorrect state or
 *     unsupported operation.
 *     <br>{@link AV_ERR_UNKNOWN}: An internal error occurs. You are advised to check logs.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_FreeOutputBuffer(OH_AVCodec *codec, uint32_t index);

/**
 * @brief Checks whether an audio codec instance is valid.
 *
 * This function is used to detect the codec status when a background fault is rectified or an application is
 * switched from the background.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param isValid Pointer to an instance of the Boolean type. The value **true** means that the codec instance is
 *     valid, and **false** means the opposite.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: An input parameter is nullptr or invalid.
 * @since 11
 */
OH_AVErrCode OH_AudioCodec_IsValid(OH_AVCodec *codec, bool *isValid);

/**
 * @brief Sets the decryption information.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param mediaKeySession Pointer to the media key session with the decryption feature.
 * @param secureAudio Whether a secure decoder is used. **true** if used, **false** otherwise.
 *     <br>Currently, the secure decoder is not supported for audio decryption.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: The OH_AVCodec instance is nullptr or invalid, or the mediaKeySystemInfo
 *     instance is nullptr or invalid.
 *     <br>{@link AV_ERR_INVALID_STATE}: The codec service is unavailable.
 *     <br>{@link AV_ERR_NO_MEMORY}: Memory allocation fails.
 * @since 12
 * @version 1.0
*/
OH_AVErrCode OH_AudioCodec_SetDecryptionConfig(OH_AVCodec *codec, MediaKeySession *mediaKeySession,
    bool secureAudio);

/**
 * @brief Obtains the index of an available input buffer for an audio codec within the specified timeout period.
 *
 * After obtaining the index, call {@link OH_AudioCodec_GetInputBuffer} to obtain the buffer corresponding to the
 * index.
 *
 * After the buffer is filled, call {@link OH_AudioCodec_PushInputBuffer} with the same index to push the buffer to
 * the codec.
 *
 * Note: This function can be used only in synchronous mode of the audio codec.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param index Pointer to the index of the input buffer obtained.
 * @param timeoutUs Timeout period, in microseconds. A negative value means to wait infinitely.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: The operation fails due to incorrect input parameters.
 *     <br>{@link AV_ERR_INVALID_STATE}: The operation fails due to an invalid state, for example, the codec not being
 *     started.
 *     <br>{@link AV_ERR_OPERATE_NOT_PERMIT}: The operation fails because the call is not allowed in asynchronous mode.
 *     <br>{@link AV_ERR_TRY_AGAIN_LATER}: The operation fails because no available buffer is obtained within the
 *     timeout period.
 * @since 20
 */
OH_AVErrCode OH_AudioCodec_QueryInputBuffer(struct OH_AVCodec *codec, uint32_t *index, int64_t timeoutUs);

/**
 * @brief Obtains the input buffer identified by **index** for an audio codec. Note: This function can be used only in
 * synchronous mode of the audio codec.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param index Index of the input buffer. It is obtained by calling {@link OH_AudioCodec_QueryInputBuffer}.
 * @return Pointer to the OH_AVBuffer instance created. If the operation fails, NULL is returned.
 * @since 20
 */
OH_AVBuffer *OH_AudioCodec_GetInputBuffer(struct OH_AVCodec *codec, uint32_t index);

/**
 * @brief Obtains the index of an available output buffer for an audio codec within the specified timeout period. After
 * obtaining the index, call {@link OH_AudioCodec_GetOutputBuffer} to obtain the buffer corresponding to the index.
 *
 * After the use, call {@link OH_AudioCodec_FreeOutputBuffer} to release the buffer. Once released, the buffer
 * cannot be reused. Prolonged failure to release buffers will block the codec process. Note: This function can be used
 * only in synchronous mode of the audio codec.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param index Pointer to the index of the output buffer obtained.
 * @param timeoutUs Timeout period, in microseconds. A negative value means to wait infinitely.
 * @return {@link AV_ERR_OK}: The operation is successful.
 *     <br>{@link AV_ERR_INVALID_VAL}: The operation fails due to incorrect input parameters.
 *     <br>{@link AV_ERR_INVALID_STATE}: The operation fails due to an invalid state, for example, the codec not being
 *     started.
 *     <br>{@link AV_ERR_OPERATE_NOT_PERMIT}: The operation fails because the call is not allowed in asynchronous mode.
 *     <br>{@link AV_ERR_STREAM_CHANGED}: The format of the decoded output stream changes. You can call
 *     {@link OH_AudioCodec_GetOutputDescription} to obtain the new stream information.
 *     <br>{@link AV_ERR_TRY_AGAIN_LATER}: The operation fails because no available buffer is obtained within the
 *     timeout period.
 * @since 20
 */
OH_AVErrCode OH_AudioCodec_QueryOutputBuffer(struct OH_AVCodec *codec, uint32_t *index, int64_t timeoutUs);

/**
 * @brief Obtains the output buffer identified by **index** for an audio codec. Note: This function can be used only in
 * synchronous mode of the audio codec.
 *
 * @param codec Pointer to an OH_AVCodec instance.
 * @param index Index of the output buffer. It is obtained by calling {@link OH_AudioCodec_QueryOutputBuffer}.
 * @return Pointer to the OH_AVBuffer instance created. If the operation fails, NULL is returned.
 * @since 20
 */
OH_AVBuffer *OH_AudioCodec_GetOutputBuffer(struct OH_AVCodec *codec, uint32_t index);
#ifdef __cplusplus
}
#endif
#endif // NATIVE_AVCODEC_AUDIOCODEC_H
/** @} */